"""Add Prompt table and drift tracking

Revision ID: 8e04adb058c9
Revises: c4641f32a395
Create Date: 2026-01-19 11:38:08.286914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e04adb058c9'
down_revision: Union[str, Sequence[str], None] = 'c4641f32a395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('last_csc_hash', sa.String(), nullable=False),
    sa.Column('last_csc_content', sa.Text(), nullable=False),
    sa.Column('drift_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_hash'), 'prompts', ['hash'], unique=True)
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_hash'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
