"""add_missing_user_columns

Revision ID: 94cc1c9c2b88
Revises: 8e04adb058c9
Create Date: 2026-01-21 02:05:17.738718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94cc1c9c2b88'
down_revision: Union[str, Sequence[str], None] = '8e04adb058c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('raw_tokens',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('compressed_tokens',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('savings_ratio',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=True)
        batch_op.alter_column('latency_ms',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=True)
        batch_op.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(),
                   nullable=True)

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('hash',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('raw_text',
                   existing_type=sa.TEXT(),
                   nullable=True)
        batch_op.alter_column('last_csc_hash',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('last_csc_content',
                   existing_type=sa.TEXT(),
                   nullable=True)
        batch_op.alter_column('drift_count',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('last_updated',
                   existing_type=postgresql.TIMESTAMP(),
                   nullable=True)

    # SQLite supports ADD COLUMN without batch, which avoids CircularDependencyError in batch mode
    # op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('tier', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('usage_count', sa.Integer(), nullable=True))
    # op.add_column('users', sa.Column('max_usage', sa.Integer(), nullable=True))
    # op.add_column('users', sa.Column('subscription_plan', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('subscription_expiry', sa.DateTime(), nullable=True))
    # op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    # op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('is_active',
    #                existing_type=sa.BOOLEAN(),
    #                nullable=True)
    #     batch_op.alter_column('created_at',
    #                existing_type=postgresql.TIMESTAMP(),
    #                nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(),
                   nullable=False)
        batch_op.alter_column('is_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=False)
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('subscription_expiry')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('max_usage')
        batch_op.drop_column('usage_count')
        batch_op.drop_column('tier')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
                   existing_type=postgresql.TIMESTAMP(),
                   nullable=False)
        batch_op.alter_column('drift_count',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('last_csc_content',
                   existing_type=sa.TEXT(),
                   nullable=False)
        batch_op.alter_column('last_csc_hash',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('raw_text',
                   existing_type=sa.TEXT(),
                   nullable=False)
        batch_op.alter_column('hash',
                   existing_type=sa.VARCHAR(),
                   nullable=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(),
                   nullable=False)
        batch_op.alter_column('latency_ms',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=False)
        batch_op.alter_column('savings_ratio',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=False)
        batch_op.alter_column('compressed_tokens',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('raw_tokens',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###
